# -*- coding: utf-8 -*-
# Motoreign Multi Vendor Marketplace - Odoo 19 Enterprise
{
    'name': "Motoreign Multi Vendor Marketplace",
    'version': "19.0.1.0.0",
    'category': 'eCommerce',
    'summary': 'Multi Vendor Marketplace for Odoo 19 | Seller Management | Commission | eCommerce',
    'description': """Motoreign Multi Vendor Marketplace enables businesses to run a full
        multi-vendor eCommerce platform on Odoo 19 Enterprise.""",
    'author': 'Motoreign',
    'company': 'Motoreign',
    'maintainer': 'Motoreign',
    'website': 'https://motoreign.com',
    'depends': [
        'base', 'sale_management', 'account', 'website',
        'stock', 'website_sale', 'sale_pdf_quote_builder', 'auth_signup',
    ],
    'data': [
        'security/multi_vendor_marketplace_groups.xml',
        'security/inventory_request_security.xml',
        'security/product_template_security.xml',
        'security/sale_order_line_security.xml',
        'security/seller_payment_security.xml',
        'security/seller_shop_security.xml',
        'security/stock_picking_security.xml',
        'security/ir.model.access.csv',
        'data/res_users_data.xml',
        'data/ir_config_parameter_data.xml',
        'data/social_media_data.xml',
        'data/account_journal_data.xml',
        'data/product_template_data.xml',
        'data/email_template_data.xml',
        'data/website_menu_data.xml',
        'views/vendor_dashboard_views.xml',
        'views/stock_moves_views.xml',
        'views/sell_page_templates.xml',
        'views/res_partner_views.xml',
        'views/seller_payment_views.xml',
        'views/request_payment_views.xml',
        'views/multi_vendor_pricelist_views.xml',
        'views/product_product_views.xml',
        'views/product_template_views.xml',
        'views/seller_shop_views.xml',
        'views/res_config_settings_views.xml',
        'views/seller_review_views.xml',
        'views/helpful_info_views.xml',
        'views/product_public_category_views.xml',
        'views/account_payment_method_views.xml',
        'views/stock_picking_views.xml',
        'views/inventory_request_views.xml',
        'views/seller_recommend_views.xml',
        'views/social_media_views.xml',
        'views/seller_web_templates.xml',
        'views/seller_product_templates.xml',
        'views/sale_order_line_views.xml',
        'views/multi_vendor_marketplace_menus.xml',
        'views/seller_shop_information_templates.xml',
        'views/seller_list_templates.xml',
        'wizard/settings_view_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'motoreign_marketplace/static/src/xml/seller_dashboard.xml',
            'motoreign_marketplace/static/src/js/seller_dashboard_action.js',
        ],
        'web.assets_frontend': [
            'motoreign_marketplace/static/src/js/rating.js',
            'motoreign_marketplace/static/src/scss/partner_rating.scss',
        ],
    },
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_hook',
}
